package c.z
import android.app.*;import android.graphics.Color.*;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import org.json.*;import java.util.*;import java.lang.reflect.*;import kotlin.math.*;
class M:AppCompatActivity(){val H=ArrayList<Any?>();val L=Array(3){HashSet<String>()};lateinit var w:WebView;lateinit var b:Button;var m=0;var s=true;val P by lazy{getSharedPreferences("Z",0)};val h=Handler(Looper.getMainLooper())
override fun onCreate(k:Bundle?){super.onCreate(k);H.add(this);(0..2).forEach{i->L[i].addAll(P.getString("$i","")!!.split(","))};m=P.getInt("M",0);s=P.getBoolean("S",true);val f=FrameLayout(this);w=WebView(this).apply{settings.javaScriptEnabled=true;settings.domStorageEnabled=true;webViewClient=WebViewClient();addJavascriptInterface(this@M,"K")};b=Button(this).apply{text="⚙";setTextColor(-1);setBackgroundColor(0x99000000.toInt());layoutParams=FrameLayout.LayoutParams(120,120,53);setOnClickListener{e()}};f.addView(w);f.addView(b);setContentView(f);v(m);w.loadDataWithBaseURL(null,"""<!DOCTYPE html><title>HTML/App Realizer</title><style>body{margin:0;padding:4px;background:#111;font-family:monospace}div{min-height:40vh;background:#222;color:#eee;border:solid #444;padding:8px;white-space:pre-wrap;margin-bottom:4px;overflow:auto}button{border:0;background:#058;color:#fff;width:100%;height:5vh;font-size:2vh}</style><div id=i contenteditable="plaintext-only" oninput="c.textContent=i.textContent.length"></div><button onclick="var code=i.textContent;document.open();document.write(code);document.close()">Realize (<b id=c>0</b> characters)</button>""","text/html","utf-8",null)}
override fun onResume(){super.onResume();if(m==1)v(0)};override fun onKeyDown(k:Int,e:KeyEvent?):Boolean{if(k==24){b.visibility=0;h.removeCallbacksAndMessages(null);h.postDelayed({v(m)},3000);return true};return super.onKeyDown(k,e)}
fun v(n:Int){m=n;P.edit().putInt("M",m).apply();b.visibility=if(m==0)0 else 8}
fun e(){val l=LinearLayout(this).apply{orientation=1;padding=50;setBackgroundColor(-13421773)};l.addView(Button(this).apply{text="BOX: ${if(s)"ON" else "OFF"}";setBackgroundColor(if(s)-16711936 else -65536);setTextColor(-1);setOnClickListener{s=!s;P.edit().putBoolean("S",s).apply();text="BOX: ${if(s)"ON" else "OFF"}";setBackgroundColor(if(s)-16711936 else -65536)}});val t={i:Int->val x=EditText(this).apply{setText(L[i].joinToString(","))};AlertDialog.Builder(this).setTitle(arrayOf("BL","WL","GL")[i]).setView(x).setPositiveButton("OK"){_,_->L[i].clear();L[i].addAll(x.text.split(","));P.edit().putString("$i",x.text.toString()).apply()}.show()};(0..2).forEach{i->l.addView(Button(this).apply{text="Edit "+arrayOf("BL","WL","GL")[i];setTextColor(-1);setOnClickListener{t(i)}})};arrayOf("Vis","Focus","Open","Perma").forEachIndexed{i,x->l.addView(Button(this).apply{text=x;setTextColor(-1);setOnClickListener{v(i)}})};AlertDialog.Builder(this).setView(l).show()}
@JavascriptInterface fun s(n:Int)=runOnUiThread{v(min(m,n.coerceIn(0,3)))}
@JavascriptInterface fun ask(p:String){if(!s)requestPermissions(arrayOf("android.permission.${p.uppercase()}"),1)}
@JavascriptInterface fun del(p:Int){if(p>0&&p<H.size)H[p]=null}
@JavascriptInterface fun c(n:String):String{if(s)return "E:BOX";return try{H.add(Class.forName(n));"P${H.size-1}"}catch(e:Exception){"E$e"}}
@JavascriptInterface fun l(n:String,id:Int):String{if(s)return "E:BOX";return try{val i=Class.forName(n);val p=Proxy.newProxyInstance(i.classLoader,arrayOf(i)){_,m,a->val pts=a?.map{H.add(it);"P${H.size-1}"}?.joinToString(",")?:"";runOnUiThread{w.evaluateJavascript("window.onL($id,'${m.name}','$pts')",null)};null};H.add(p);"P${H.size-1}"}catch(e:Exception){"E$e"}}
@JavascriptInterface fun x(p:Int,n:String,j:String):String{if(s)return "E:BOX";val o=H[p]?:return "E:NULL";val sig="$n ${o.javaClass.name}".lowercase();if(L[0].any{it!=""&&sig.contains(it)})return "E:BL";if(L[1].any{it!=""&&sig.contains(it)})return r(p,n,j);val g=L[2].find{it!=""&&sig.contains(it)}?:if(L[0].isEmpty()&&L[1].isEmpty())"ALL" else null;if(g!=null){val i=(System.currentTimeMillis()%99999).toInt();runOnUiThread{AlertDialog.Builder(this).setTitle("REQ").setMessage(sig).setPositiveButton("ONCE"){_,_->cb(i,r(p,n,j))}.setNeutralButton("ALWAYS"){_,_->L[1].add(g);P.edit().putString("1",L[1].joinToString(",")).apply();cb(i,r(p,n,j))}.setNegativeButton("BLOCK"){_,_->L[0].add(g);P.edit().putString("0",L[0].joinToString(",")).apply();cb(i,"E:BL")}.setCancelable(false).show()};return "W:$i"};return r(p,n,j)}
fun r(p:Int,n:String,j:String):String{try{val o=H[p]!!;val c=if(o is Class<*>)o else o.javaClass;val a=JSONArray(j);val l=a.length();val ms=c.methods.filter{it.name==n&&it.parameterTypes.size==l};if(ms.isEmpty())return "E:NM";for(mt in ms){try{val v=arrayOfNulls<Any>(l);val t=mt.parameterTypes;for(i in 0 until l){val raw=a.get(i);v[i]=if(raw is String&&(raw.startsWith("*")||raw.startsWith("P")))H[raw.substring(1).toInt()]else when(t[i]){Int::class.javaPrimitiveType->raw.toString().toInt();Long::class.javaPrimitiveType->raw.toString().toLong();Float::class.javaPrimitiveType->raw.toString().toFloat();Double::class.javaPrimitiveType->raw.toString().toDouble();Boolean::class.javaPrimitiveType->raw.toString().toBoolean();else->raw}}
val z=mt.invoke(if(o is Class<*>)null else o,*v);if(z==null||z is Unit)return "N";if(z is Number||z is String||z is Boolean)return "V$z";H.add(z);return "P${H.size-1}"}catch(e:Exception){continue}};return "E:SIG_MISMATCH"}catch(e:Exception){return "E:$e"}}
fun cb(i:Int,r:String)=w.evaluateJavascript("window.onC($i,'${r.replace("'","\\'")}')",null)}
